id: P4A01CB1A
initial_creation_type: input
source_metadata:
  title: Khenchen Tashi Özer Series
  language: bo
  description: 'Texts by Khenchen Tashi Özer (mkhan chen bkra shis ''od zer, 1836–1910),
    the renowned disciple of Kongtrul Lodrö Thaye and others:'
  volume:
    2081f545e6cb460799d46faabcd5dbc4:
      title: Advice for Satsa Drupgen
      parent: Advice
created_at: '2022-03-01T00:23:22.342480'
last_modified_at: '2022-03-01T00:23:22.342483'
statistics:
  total_words: 215
  total_non_words: 21
quality:
  non_words_ratio: 0.1
